✨ feat: SQ-65941 [front] Criar componente do guia de apresentação - 1
squidit/react-css pull request #36
Opened 2024-09-24 17:30 UTC by wandersonsales-dev

**Link da Tarefa:**

[SQ-65941](https://duopana.myjetbrains.com/youtrack/issue/SQ-65941/front-Criar-componente-do-guia-de-apresentacao-1) 

- [x] O PR está com o nome no formato **(SQ-12345) Título da Tarefa**
- [x] Foi completamente testado
- [x] Merge do branch **master** foi feito antes do PR ser criado

## Documentação:

- [ ] Criou novos componentes? foi criado a documentação (.md)
- [ ] Criou testes para os novos componentes

## Evidências de Teste:

https://www.awesomescreenshot.com/video/31866218?key=fea4469965fa31a9fd58d47d0105724c

- [x] Possui evidências na tarefa

2024-09-24 17:33 UTC, wandersonsales-dev commented on src/components/sq-modal/sq-modal.component.scss
> +}
It's not necessary

2024-09-24 17:33 UTC, wandersonsales-dev commented on src/components/sq-modal/sq-modal.component.scss
> +}
It's not necessary

2024-09-24 17:34 UTC, wandersonsales-dev commented on src/components/sq-modal-welcome-creators-insights/__docs__/sq-modal-steps.component.stories.tsx
> +}
Done :rocket:

2024-09-24 17:34 UTC, wandersonsales-dev commented on src/components/sq-flow/sq-flow.component.tsx
> +                ></li>
It's not necessary

2024-09-24 17:35 UTC, wandersonsales-dev commented on src/components/sq-flow/sq-flow.component.tsx
> +          : null}
It's not necessary

2024-09-24 17:35 UTC, wandersonsales-dev commented on src/components/sq-modal-welcome-creators-insights/sq-modal-welcome-creators-insights.component.scoped.scss
> +    }
This value should be fixed

2024-09-24 17:35 UTC, wandersonsales-dev commented on src/components/sq-modal-welcome-creators-insights/sq-modal-welcome-creators-insights.component.scoped.scss
> +    }
It's not necessary

2024-09-24 17:37 UTC, wandersonsales-dev commented on src/components/sq-modal-welcome-creators-insights/sq-modal-welcome-creators-insights.component.scoped.scss
> +  }
This causes a different behavior than desired. When using top the space previously occupied at the end of the div will still be considered, while with margin-top this does not happen.

2024-09-24 17:37 UTC, wandersonsales-dev commented on src/components/sq-modal-welcome-creators-insights/__docs__/sq-modal-steps.component.example.tsx
> +  )
Done :rocket:

2024-09-24 17:54 UTC, elianefaveron1 approved these changes

2024-09-24 18:29 UTC, wandersonsales-dev commented
@JonasPeres code review

2024-09-24 19:30 UTC, htamagnus submitted a review, later dismissed

2024-09-24 22:06 UTC, JonasPeres submitted a review, later dismissed

2024-09-25 18:22 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-welcome-creators-insights/__docs__/sq-modal-welcome-creators-insights.component.stories.tsx
> +}
It's not necessary

2024-09-25 18:23 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-welcome-creators-insights/sq-modal-welcome-creators-insights.component.scoped.scss
> +    flex-direction: column;
It's wrong

2024-09-25 18:23 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-welcome-creators-insights/sq-modal-welcome-creators-insights.component.scoped.scss
> +  }
It's wrong

2024-09-25 18:23 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-welcome-creators-insights/__docs__/sq-modal-welcome-creators-insights.component.example.tsx
> +    >
It's not necessary

2024-09-25 18:23 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-welcome-creators-insights/__docs__/sq-modal-welcome-creators-insights.component.example.tsx
> +    </div>
It's not necessary

2024-09-25 18:25 UTC, htamagnus submitted a review, later dismissed

2024-09-25 19:56 UTC, wandersonsales-dev commented
@JonasPeres code review

2024-09-25 20:24 UTC, JonasPeres approved these changes

2024-09-26 13:17 UTC, JonasPeres approved these changes

2024-09-26 13:19 UTC, htamagnus submitted a review, later dismissed

2024-09-26 16:57 UTC, elianefaveron1 approved these changes

2024-09-26 16:58 UTC, elianefaveron1 requested changes
Tem conflitos

2024-09-27 12:42 UTC, htamagnus reviewed
só precisa resolver o conflito

2024-09-27 12:47 UTC, htamagnus approved these changes

2024-09-27 16:13 UTC, JonasPeres approved these changes

2024-09-27 16:30 UTC, elianefaveron1 approved these changes

2024-09-27 16:30 UTC, merged