add SqModalActivation component
squidit/react-css pull request #43
Opened 2024-10-04 18:16 UTC by htamagnus

**Link da Tarefa:**

![image](https://github.com/user-attachments/assets/227335fc-f8d9-448c-bc2b-3a1d77880829)

[](url) 

- [ ] O PR está com o nome no formato **(SQ-12345) Título da Tarefa**
- [ ] Foi completamente testado
- [ ] Merge do branch **master** foi feito antes do PR ser criado

## Documentação:

- [ ] Criou novos componentes? foi criado a documentação (.md)
- [ ] Criou testes para os novos componentes

## Evidências de Teste:

- [ ] Possui evidências na tarefa
-

2024-10-04 19:17 UTC, wandersonsales-dev approved these changes

2024-10-04 19:17 UTC, wandersonsales-dev requested changes
sobe a versão

2024-10-04 20:13 UTC, wandersonsales-dev approved these changes

2024-10-04 20:14 UTC, htamagnus commented
code review @mclmorais

2024-10-04 22:40 UTC, htamagnus commented
code review @JonasPeres

2024-10-07 11:28 UTC, elianefaveron1 approved these changes

2024-10-07 11:36 UTC, htamagnus commented
code review @JonasPeres

2024-10-07 11:51 UTC, JonasPeres approved these changes

2024-10-07 11:51 UTC, merged