✨ feat: SQ-66409 [creators insights] eventos do GA4 no modal de ativação
squidit/react-css pull request #51
Opened 2024-10-15 11:48 UTC by wandersonsales-dev

**Link da Tarefa:**

[SQ-66409](https://duopana.myjetbrains.com/youtrack/issue/SQ-66409) [creators insights] eventos do GA4 no modal de ativação

- [x] O PR está com o nome no formato **(SQ-12345) Título da Tarefa**
- [x] Foi completamente testado
- [x] Merge do branch **master** foi feito antes do PR ser criado

## Documentação:

- [x] Criou novos componentes? foi criado a documentação (.md)
- [ ] Criou testes para os novos componentes

2024-10-15 11:49 UTC, elianefaveron1 approved these changes

2024-10-15 11:49 UTC, wandersonsales-dev commented
@evertondsantos code review

2024-10-15 11:53 UTC, wandersonsales-dev commented on src/helpers/data-layer/data-layer.helper.ts
> +  }
It's not necessary

2024-10-15 16:47 UTC, evertondsantos requested changes

2024-10-15 16:47 UTC, evertondsantos commented on src/interfaces/sq-data-layer.interface.ts
> +  dataLayer?: any[]
Não tem como tipa essa cara aqui ?

2024-10-15 17:15 UTC, wandersonsales-dev commented on src/interfaces/sq-data-layer.interface.ts
> +  dataLayer?: any[]
Esse aí a gente pode receber qualquer coisa realmente. Depende da necessidade do pessoal de capturar esses dados no GA

2024-10-15 17:16 UTC, wandersonsales-dev commented on src/interfaces/sq-data-layer.interface.ts
> +  dataLayer?: any[]
A gente tá até tentando pensar num formato que seja mais previsível pra colocar tipagem depois

2024-10-15 17:21 UTC, evertondsantos commented on src/interfaces/sq-data-layer.interface.ts
> +  dataLayer?: any[]
Entendi, então adicionar um `// TODO:  `para depois a gente não esquece desse cara.

2024-10-16 12:02 UTC, wandersonsales-dev commented on src/interfaces/sq-data-layer.interface.ts
> +  dataLayer?: any[]
Feito :rocket:

2024-10-16 12:03 UTC, wandersonsales-dev commented
@evertondsantos code review

2024-10-16 17:06 UTC, merged