✨ feat: SQ-66819 CI [react-css] - Permitir a configuração de visualização pública
squidit/react-css pull request #63
Opened 2024-11-04 19:48 UTC by wandersonsales-dev

**Link da Tarefa:**

[SQ-66819](https://duopana.myjetbrains.com/youtrack/issue/SQ-66819) CI [react-css] - Permitir a configuração de visualização pública

- [x] O PR está com o nome no formato **(SQ-12345) Título da Tarefa**
- [x] Foi completamente testado
- [x] Merge do branch **master** foi feito antes do PR ser criado

## Documentação:

- [ ] Criou novos componentes? foi criado a documentação (.md)
- [ ] Criou testes para os novos componentes

## Evidências de Teste:

- [ ] Possui evidências na tarefa
-

2024-11-04 20:03 UTC, elianefaveron1 requested changes

2024-11-04 20:03 UTC, elianefaveron1 commented on src/components-creators-insights/sq-modal-activation/sq-modal-activation.component.tsx
> +              <SqSocialConnect profiles={mapProfilesToSocialConnect([profile])} style={{ width: '40px', height: '40px' }} />
esse css inline não seria melhor colocar em um arquivo css separado?

2024-11-04 20:03 UTC, elianefaveron1 commented on src/components-creators-insights/sq-modal-activation/sq-modal-activation.component.tsx
> +                    onToggleCreatorsInsights(profile.profileId, profile.socialNetwork, profile.hasCreatorsInsights)
veja essa sugestão

2024-11-04 20:03 UTC, elianefaveron1 commented on src/components-creators-insights/sq-modal-activation/sq-modal-activation.component.tsx
> +                  }
aqui também

2024-11-04 20:03 UTC, elianefaveron1 reviewed
Precisa alterar o version também

2024-11-04 20:23 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-activation/sq-modal-activation.component.tsx
> +                  }
Feito :rocket:

2024-11-04 20:24 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-activation/sq-modal-activation.component.tsx
> +                    onToggleCreatorsInsights(profile.profileId, profile.socialNetwork, profile.hasCreatorsInsights)
Feito :rocket:

2024-11-04 20:27 UTC, wandersonsales-dev commented
> Precisa alterar o version também

Alterei para a versão 1.2.11. A última era a 1.2.10. É isso, não?!

2024-11-05 13:25 UTC, wandersonsales-dev commented on src/components-creators-insights/sq-modal-activation/sq-modal-activation.component.tsx
> +                  onChange={() => onTogglePublicProfile?.(profile.profileId, profile.socialNetwork, profile.hasCreatorsInsights)}
Feito :rocket:

2024-11-05 16:49 UTC, wandersonsales-dev commented
@evertondsantos code review

2024-11-05 18:35 UTC, evertondsantos approved these changes

2024-11-05 19:56 UTC, merged