🔧 SQ-66927 [Ajuste] CI - Levar em consideração o token para na ativação da view púplica
squidit/react-css pull request #66
Opened 2024-11-07 18:33 UTC by wandersonsales-dev

**Link da Tarefa:**

[SQ-66927](https://duopana.myjetbrains.com/youtrack/issue/SQ-66927) [Ajuste] CI - Levar em consideração o token para na ativação da view púplica

- [x] O PR está com o nome no formato **(SQ-12345) Título da Tarefa**
- [x] Foi completamente testado
- [x] Merge do branch **master** foi feito antes do PR ser criado

## Documentação:

- [ ] Criou novos componentes? foi criado a documentação (.md)
- [ ] Criou testes para os novos componentes

## Evidências de Teste:

- [ ] Possui evidências na tarefa
-

2024-11-07 18:41 UTC, htamagnus approved these changes

2024-11-07 18:47 UTC, wandersonsales-dev commented
@evertondsantos code review

2024-11-07 20:39 UTC, elianefaveron1 approved these changes

2024-11-07 20:39 UTC, wandersonsales-dev commented
@evertondsantos code review

2024-11-07 20:43 UTC, htamagnus approved these changes

2024-11-07 20:57 UTC, evertondsantos requested changes

2024-11-07 20:57 UTC, evertondsantos commented on src/components/sq-menu-options/sq-menu-options.component.tsx
>          onClick={() => setOpen(!open)}
Não teria que adicionar a propriedade disabled no botão também ?

2024-11-08 12:27 UTC, wandersonsales-dev commented on src/components/sq-menu-options/sq-menu-options.component.tsx
>          onClick={() => setOpen(!open)}
Melhor, só por garantia. A classe disabled já trata os cenários que a gente precisa bloqueando o clique e estilizando o botão. Mas com o disabled como prop do botão garantiria

2024-11-08 12:44 UTC, wandersonsales-dev commented on src/components/sq-menu-options/sq-menu-options.component.tsx
>          onClick={() => setOpen(!open)}
feito 🚀

2024-11-08 13:29 UTC, evertondsantos approved these changes

2024-11-08 14:04 UTC, merged